export const brand = {
  logoUrl: 'https://clinik.club/email/clinik-club-logo.png',
  siteUrl: 'https://clinik.club',
  primary: '#0889b2',
  mint: '#54d6ad',
  bgOuter: '#f3fbff',
  textDark: '#0f2a36',
  textMuted: '#55707d',
}

export const styles = {
  main: { backgroundColor: '#ffffff', fontFamily: 'Inter, Arial, sans-serif' } as const,
  outer: { backgroundColor: '#f3fbff', padding: '32px 16px' } as const,
  container: {
    backgroundColor: '#ffffff',
    maxWidth: '560px',
    margin: '0 auto',
    borderRadius: '12px',
    border: '1px solid #e3f0f5',
    overflow: 'hidden' as const,
  },
  header: { padding: '24px 28px 0' } as const,
  logo: { height: '32px', width: 'auto' } as const,
  body: { padding: '24px 28px 28px' } as const,
  h1: {
    fontSize: '22px',
    fontWeight: 700 as const,
    color: '#0f2a36',
    margin: '0 0 16px',
    lineHeight: '1.3',
  } as const,
  text: {
    fontSize: '15px',
    color: '#3a5663',
    lineHeight: '1.6',
    margin: '0 0 16px',
  } as const,
  button: {
    backgroundColor: '#0889b2',
    color: '#ffffff',
    fontSize: '15px',
    fontWeight: 600 as const,
    borderRadius: '8px',
    padding: '12px 22px',
    textDecoration: 'none',
    display: 'inline-block',
  } as const,
  link: { color: '#0889b2', textDecoration: 'underline' } as const,
  code: {
    fontFamily: 'ui-monospace, Menlo, monospace',
    fontSize: '26px',
    letterSpacing: '6px',
    fontWeight: 700 as const,
    color: '#0889b2',
    backgroundColor: '#f3fbff',
    border: '1px solid #d6ecf2',
    borderRadius: '8px',
    padding: '14px 18px',
    display: 'inline-block',
    margin: '0 0 16px',
  } as const,
  footer: {
    fontSize: '12px',
    color: '#7a8f99',
    margin: '24px 0 0',
    lineHeight: '1.5',
  } as const,
  hr: { borderColor: '#e3f0f5', margin: '24px 0' } as const,
}