/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as FSlugRouteImport } from './routes/f.$slug'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppCuponsRouteImport } from './routes/_authenticated/app.cupons'
import { Route as AuthenticatedAppCrmRouteImport } from './routes/_authenticated/app.crm'
import { Route as AuthenticatedAppContaRouteImport } from './routes/_authenticated/app.conta'
import { Route as AuthenticatedAppAdminRouteImport } from './routes/_authenticated/app.admin'
import { Route as AuthenticatedAppCrmIndexRouteImport } from './routes/_authenticated/app.crm.index'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as AuthenticatedAppCrmUpgradeRouteImport } from './routes/_authenticated/app.crm.upgrade'
import { Route as AuthenticatedAppCrmRelatoriosRouteImport } from './routes/_authenticated/app.crm.relatorios'
import { Route as AuthenticatedAppCrmPipelinesRouteImport } from './routes/_authenticated/app.crm.pipelines'
import { Route as AuthenticatedAppCrmLeadsRouteImport } from './routes/_authenticated/app.crm.leads'
import { Route as AuthenticatedAppCrmConfiguracoesRouteImport } from './routes/_authenticated/app.crm.configuracoes'
import { Route as AuthenticatedAppAdminPagamentosRouteImport } from './routes/_authenticated/app.admin.pagamentos'
import { Route as AuthenticatedAppFunisIdLeadsRouteImport } from './routes/_authenticated/app.funis.$id.leads'
import { Route as AuthenticatedAppFunisIdEditarRouteImport } from './routes/_authenticated/app.funis.$id.editar'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const FSlugRoute = FSlugRouteImport.update({
  id: '/f/$slug',
  path: '/f/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppCuponsRoute = AuthenticatedAppCuponsRouteImport.update({
  id: '/cupons',
  path: '/cupons',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppCrmRoute = AuthenticatedAppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppContaRoute = AuthenticatedAppContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAdminRoute = AuthenticatedAppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppCrmIndexRoute =
  AuthenticatedAppCrmIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppCrmRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppCrmUpgradeRoute =
  AuthenticatedAppCrmUpgradeRouteImport.update({
    id: '/upgrade',
    path: '/upgrade',
    getParentRoute: () => AuthenticatedAppCrmRoute,
  } as any)
const AuthenticatedAppCrmRelatoriosRoute =
  AuthenticatedAppCrmRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => AuthenticatedAppCrmRoute,
  } as any)
const AuthenticatedAppCrmPipelinesRoute =
  AuthenticatedAppCrmPipelinesRouteImport.update({
    id: '/pipelines',
    path: '/pipelines',
    getParentRoute: () => AuthenticatedAppCrmRoute,
  } as any)
const AuthenticatedAppCrmLeadsRoute =
  AuthenticatedAppCrmLeadsRouteImport.update({
    id: '/leads',
    path: '/leads',
    getParentRoute: () => AuthenticatedAppCrmRoute,
  } as any)
const AuthenticatedAppCrmConfiguracoesRoute =
  AuthenticatedAppCrmConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAppCrmRoute,
  } as any)
const AuthenticatedAppAdminPagamentosRoute =
  AuthenticatedAppAdminPagamentosRouteImport.update({
    id: '/pagamentos',
    path: '/pagamentos',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppFunisIdLeadsRoute =
  AuthenticatedAppFunisIdLeadsRouteImport.update({
    id: '/funis/$id/leads',
    path: '/funis/$id/leads',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFunisIdEditarRoute =
  AuthenticatedAppFunisIdEditarRouteImport.update({
    id: '/funis/$id/editar',
    path: '/funis/$id/editar',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/contato': typeof ContatoRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/checkout/return': typeof CheckoutReturnRoute
  '/f/$slug': typeof FSlugRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/app/admin': typeof AuthenticatedAppAdminRouteWithChildren
  '/app/conta': typeof AuthenticatedAppContaRoute
  '/app/crm': typeof AuthenticatedAppCrmRouteWithChildren
  '/app/cupons': typeof AuthenticatedAppCuponsRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/admin/pagamentos': typeof AuthenticatedAppAdminPagamentosRoute
  '/app/crm/configuracoes': typeof AuthenticatedAppCrmConfiguracoesRoute
  '/app/crm/leads': typeof AuthenticatedAppCrmLeadsRoute
  '/app/crm/pipelines': typeof AuthenticatedAppCrmPipelinesRoute
  '/app/crm/relatorios': typeof AuthenticatedAppCrmRelatoriosRoute
  '/app/crm/upgrade': typeof AuthenticatedAppCrmUpgradeRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/app/crm/': typeof AuthenticatedAppCrmIndexRoute
  '/app/funis/$id/editar': typeof AuthenticatedAppFunisIdEditarRoute
  '/app/funis/$id/leads': typeof AuthenticatedAppFunisIdLeadsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/contato': typeof ContatoRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/f/$slug': typeof FSlugRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/app/admin': typeof AuthenticatedAppAdminRouteWithChildren
  '/app/conta': typeof AuthenticatedAppContaRoute
  '/app/cupons': typeof AuthenticatedAppCuponsRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/admin/pagamentos': typeof AuthenticatedAppAdminPagamentosRoute
  '/app/crm/configuracoes': typeof AuthenticatedAppCrmConfiguracoesRoute
  '/app/crm/leads': typeof AuthenticatedAppCrmLeadsRoute
  '/app/crm/pipelines': typeof AuthenticatedAppCrmPipelinesRoute
  '/app/crm/relatorios': typeof AuthenticatedAppCrmRelatoriosRoute
  '/app/crm/upgrade': typeof AuthenticatedAppCrmUpgradeRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/app/crm': typeof AuthenticatedAppCrmIndexRoute
  '/app/funis/$id/editar': typeof AuthenticatedAppFunisIdEditarRoute
  '/app/funis/$id/leads': typeof AuthenticatedAppFunisIdLeadsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/contato': typeof ContatoRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/checkout/return': typeof CheckoutReturnRoute
  '/f/$slug': typeof FSlugRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/_authenticated/app/admin': typeof AuthenticatedAppAdminRouteWithChildren
  '/_authenticated/app/conta': typeof AuthenticatedAppContaRoute
  '/_authenticated/app/crm': typeof AuthenticatedAppCrmRouteWithChildren
  '/_authenticated/app/cupons': typeof AuthenticatedAppCuponsRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/admin/pagamentos': typeof AuthenticatedAppAdminPagamentosRoute
  '/_authenticated/app/crm/configuracoes': typeof AuthenticatedAppCrmConfiguracoesRoute
  '/_authenticated/app/crm/leads': typeof AuthenticatedAppCrmLeadsRoute
  '/_authenticated/app/crm/pipelines': typeof AuthenticatedAppCrmPipelinesRoute
  '/_authenticated/app/crm/relatorios': typeof AuthenticatedAppCrmRelatoriosRoute
  '/_authenticated/app/crm/upgrade': typeof AuthenticatedAppCrmUpgradeRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/_authenticated/app/crm/': typeof AuthenticatedAppCrmIndexRoute
  '/_authenticated/app/funis/$id/editar': typeof AuthenticatedAppFunisIdEditarRoute
  '/_authenticated/app/funis/$id/leads': typeof AuthenticatedAppFunisIdLeadsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/contato'
    | '/login'
    | '/planos'
    | '/privacidade'
    | '/reset-password'
    | '/sobre'
    | '/termos'
    | '/app'
    | '/checkout/return'
    | '/f/$slug'
    | '/sitemap/xml'
    | '/app/admin'
    | '/app/conta'
    | '/app/crm'
    | '/app/cupons'
    | '/app/'
    | '/app/admin/pagamentos'
    | '/app/crm/configuracoes'
    | '/app/crm/leads'
    | '/app/crm/pipelines'
    | '/app/crm/relatorios'
    | '/app/crm/upgrade'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/app/crm/'
    | '/app/funis/$id/editar'
    | '/app/funis/$id/leads'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/contato'
    | '/login'
    | '/planos'
    | '/privacidade'
    | '/reset-password'
    | '/sobre'
    | '/termos'
    | '/checkout/return'
    | '/f/$slug'
    | '/sitemap/xml'
    | '/app/admin'
    | '/app/conta'
    | '/app/cupons'
    | '/app'
    | '/app/admin/pagamentos'
    | '/app/crm/configuracoes'
    | '/app/crm/leads'
    | '/app/crm/pipelines'
    | '/app/crm/relatorios'
    | '/app/crm/upgrade'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/app/crm'
    | '/app/funis/$id/editar'
    | '/app/funis/$id/leads'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cadastro'
    | '/contato'
    | '/login'
    | '/planos'
    | '/privacidade'
    | '/reset-password'
    | '/sobre'
    | '/termos'
    | '/_authenticated/app'
    | '/checkout/return'
    | '/f/$slug'
    | '/sitemap/xml'
    | '/_authenticated/app/admin'
    | '/_authenticated/app/conta'
    | '/_authenticated/app/crm'
    | '/_authenticated/app/cupons'
    | '/_authenticated/app/'
    | '/_authenticated/app/admin/pagamentos'
    | '/_authenticated/app/crm/configuracoes'
    | '/_authenticated/app/crm/leads'
    | '/_authenticated/app/crm/pipelines'
    | '/_authenticated/app/crm/relatorios'
    | '/_authenticated/app/crm/upgrade'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/_authenticated/app/crm/'
    | '/_authenticated/app/funis/$id/editar'
    | '/_authenticated/app/funis/$id/leads'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  ContatoRoute: typeof ContatoRoute
  LoginRoute: typeof LoginRoute
  PlanosRoute: typeof PlanosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  FSlugRoute: typeof FSlugRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$slug': {
      id: '/f/$slug'
      path: '/f/$slug'
      fullPath: '/f/$slug'
      preLoaderRoute: typeof FSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/cupons': {
      id: '/_authenticated/app/cupons'
      path: '/cupons'
      fullPath: '/app/cupons'
      preLoaderRoute: typeof AuthenticatedAppCuponsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/crm': {
      id: '/_authenticated/app/crm'
      path: '/crm'
      fullPath: '/app/crm'
      preLoaderRoute: typeof AuthenticatedAppCrmRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/conta': {
      id: '/_authenticated/app/conta'
      path: '/conta'
      fullPath: '/app/conta'
      preLoaderRoute: typeof AuthenticatedAppContaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin': {
      id: '/_authenticated/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AuthenticatedAppAdminRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/crm/': {
      id: '/_authenticated/app/crm/'
      path: '/'
      fullPath: '/app/crm/'
      preLoaderRoute: typeof AuthenticatedAppCrmIndexRouteImport
      parentRoute: typeof AuthenticatedAppCrmRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/crm/upgrade': {
      id: '/_authenticated/app/crm/upgrade'
      path: '/upgrade'
      fullPath: '/app/crm/upgrade'
      preLoaderRoute: typeof AuthenticatedAppCrmUpgradeRouteImport
      parentRoute: typeof AuthenticatedAppCrmRoute
    }
    '/_authenticated/app/crm/relatorios': {
      id: '/_authenticated/app/crm/relatorios'
      path: '/relatorios'
      fullPath: '/app/crm/relatorios'
      preLoaderRoute: typeof AuthenticatedAppCrmRelatoriosRouteImport
      parentRoute: typeof AuthenticatedAppCrmRoute
    }
    '/_authenticated/app/crm/pipelines': {
      id: '/_authenticated/app/crm/pipelines'
      path: '/pipelines'
      fullPath: '/app/crm/pipelines'
      preLoaderRoute: typeof AuthenticatedAppCrmPipelinesRouteImport
      parentRoute: typeof AuthenticatedAppCrmRoute
    }
    '/_authenticated/app/crm/leads': {
      id: '/_authenticated/app/crm/leads'
      path: '/leads'
      fullPath: '/app/crm/leads'
      preLoaderRoute: typeof AuthenticatedAppCrmLeadsRouteImport
      parentRoute: typeof AuthenticatedAppCrmRoute
    }
    '/_authenticated/app/crm/configuracoes': {
      id: '/_authenticated/app/crm/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/crm/configuracoes'
      preLoaderRoute: typeof AuthenticatedAppCrmConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAppCrmRoute
    }
    '/_authenticated/app/admin/pagamentos': {
      id: '/_authenticated/app/admin/pagamentos'
      path: '/pagamentos'
      fullPath: '/app/admin/pagamentos'
      preLoaderRoute: typeof AuthenticatedAppAdminPagamentosRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/funis/$id/leads': {
      id: '/_authenticated/app/funis/$id/leads'
      path: '/funis/$id/leads'
      fullPath: '/app/funis/$id/leads'
      preLoaderRoute: typeof AuthenticatedAppFunisIdLeadsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/funis/$id/editar': {
      id: '/_authenticated/app/funis/$id/editar'
      path: '/funis/$id/editar'
      fullPath: '/app/funis/$id/editar'
      preLoaderRoute: typeof AuthenticatedAppFunisIdEditarRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppAdminRouteChildren {
  AuthenticatedAppAdminPagamentosRoute: typeof AuthenticatedAppAdminPagamentosRoute
}

const AuthenticatedAppAdminRouteChildren: AuthenticatedAppAdminRouteChildren = {
  AuthenticatedAppAdminPagamentosRoute: AuthenticatedAppAdminPagamentosRoute,
}

const AuthenticatedAppAdminRouteWithChildren =
  AuthenticatedAppAdminRoute._addFileChildren(
    AuthenticatedAppAdminRouteChildren,
  )

interface AuthenticatedAppCrmRouteChildren {
  AuthenticatedAppCrmConfiguracoesRoute: typeof AuthenticatedAppCrmConfiguracoesRoute
  AuthenticatedAppCrmLeadsRoute: typeof AuthenticatedAppCrmLeadsRoute
  AuthenticatedAppCrmPipelinesRoute: typeof AuthenticatedAppCrmPipelinesRoute
  AuthenticatedAppCrmRelatoriosRoute: typeof AuthenticatedAppCrmRelatoriosRoute
  AuthenticatedAppCrmUpgradeRoute: typeof AuthenticatedAppCrmUpgradeRoute
  AuthenticatedAppCrmIndexRoute: typeof AuthenticatedAppCrmIndexRoute
}

const AuthenticatedAppCrmRouteChildren: AuthenticatedAppCrmRouteChildren = {
  AuthenticatedAppCrmConfiguracoesRoute: AuthenticatedAppCrmConfiguracoesRoute,
  AuthenticatedAppCrmLeadsRoute: AuthenticatedAppCrmLeadsRoute,
  AuthenticatedAppCrmPipelinesRoute: AuthenticatedAppCrmPipelinesRoute,
  AuthenticatedAppCrmRelatoriosRoute: AuthenticatedAppCrmRelatoriosRoute,
  AuthenticatedAppCrmUpgradeRoute: AuthenticatedAppCrmUpgradeRoute,
  AuthenticatedAppCrmIndexRoute: AuthenticatedAppCrmIndexRoute,
}

const AuthenticatedAppCrmRouteWithChildren =
  AuthenticatedAppCrmRoute._addFileChildren(AuthenticatedAppCrmRouteChildren)

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAdminRoute: typeof AuthenticatedAppAdminRouteWithChildren
  AuthenticatedAppContaRoute: typeof AuthenticatedAppContaRoute
  AuthenticatedAppCrmRoute: typeof AuthenticatedAppCrmRouteWithChildren
  AuthenticatedAppCuponsRoute: typeof AuthenticatedAppCuponsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppFunisIdEditarRoute: typeof AuthenticatedAppFunisIdEditarRoute
  AuthenticatedAppFunisIdLeadsRoute: typeof AuthenticatedAppFunisIdLeadsRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAdminRoute: AuthenticatedAppAdminRouteWithChildren,
  AuthenticatedAppContaRoute: AuthenticatedAppContaRoute,
  AuthenticatedAppCrmRoute: AuthenticatedAppCrmRouteWithChildren,
  AuthenticatedAppCuponsRoute: AuthenticatedAppCuponsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppFunisIdEditarRoute: AuthenticatedAppFunisIdEditarRoute,
  AuthenticatedAppFunisIdLeadsRoute: AuthenticatedAppFunisIdLeadsRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CadastroRoute: CadastroRoute,
  ContatoRoute: ContatoRoute,
  LoginRoute: LoginRoute,
  PlanosRoute: PlanosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  FSlugRoute: FSlugRoute,
  SitemapXmlRoute: SitemapXmlRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
